WebCadastroProcessos/Controllers/ProcessoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebCadastroProcessos.Data;
using WebCadastroProcessos.Dto;
using WebCadastroProcessos.Models;

namespace WebCadastroProcessos.Controllers
{
    public class ProcessoController : Controller
    {
        private readonly Contexto _context;

        public ProcessoController(Contexto context)
        {
            _context = context;
        }

        public IActionResult Index(string npu, DateTime? dataCadastro, string uf, int page = 1)
        {
            int pageSize = 10;
            var processos = _context.Processo.AsQueryable();

            if (!string.IsNullOrEmpty(npu))
            {
                processos = processos.Where(p => p.Npu.Contains(npu));
            }

            if (dataCadastro.HasValue)
            {
                processos = processos.Where(p => p.DataCadastro.Date == dataCadastro.Value.Date);
            }

            if (!string.IsNullOrEmpty(uf))
            {
                processos = processos.Where(p => p.Uf == uf);
            }

            var totalCount = processos.Count();
            var totalPages = totalCount > 0 ? (int)Math.Ceiling(totalCount / (double)pageSize) : 0;

            var processosPage = processos.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentNpu = npu;
            ViewBag.CurrentDataCadastro = dataCadastro?.ToString("yyyy-MM-dd");
            ViewBag.CurrentUf = uf;
            ViewBag.Uf = this.buscarUf();

            return View(processosPage);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Processo == null)
            {
                return NotFound();
            }

            var processo = await _context.Processo
                .FirstOrDefaultAsync(m => m.Id == id);

            if (processo == null)
            {
                return NotFound();
            }

            processo.DataVisualizacao = DateTime.Now;

            _context.Update(processo);
            await _context.SaveChangesAsync();

            return View(processo);
        }

        public IActionResult Create()
        {
            ViewBag.Uf = this.buscarUf();
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processo = await _context.Processo.FindAsync(id);
            if (processo == null)
            {
                return NotFound();
            }
            var ufList = new List<SelectListItem>();
            foreach (var uf in buscarUf())
            {
                ufList.Add(new SelectListItem
                {
                    Value = uf,
                    Text = uf,
                    Selected = uf == processo.Uf
                });
            }
            ViewBag.Uf = ufList;
            var municipios = await GetMunicipios(processo.Uf);
            ViewBag.Municipios = municipios.Select(municipio => new SelectListItem
            {
                Value = municipio.Nome,
                Text = municipio.Nome,
                Selected = municipio.Nome == processo.Municipio
            }).ToList();

            return View(processo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Npu,Uf,Municipio")] Processo processo)
        {
            if (ModelState.IsValid)
            {
                processo.DataCadastro = DateTime.Now;
                _context.Add(processo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(processo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Npu,Uf,Municipio")] Processo processo)
        {
            if (id != processo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    processo.DataCadastro = DateTime.Now; // O Correto é possui outro campo "DataAtualizacao", Porém não esta definido no escopo.
                    _context.Update(processo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProcessoExists(processo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(processo);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Processo == null)
            {
                return NotFound();
            }

            var processo = await _context.Processo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (processo == null)
            {
                return NotFound();
            }

            return View(processo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Processo == null)
            {
                return Problem("Entity set 'Contexto.Processo' is null.");
            }
            var processo = await _context.Processo.FindAsync(id);
            if (processo != null)
            {
                _context.Processo.Remove(processo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProcessoExists(int id)
        {
            return (_context.Processo?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpGet]
        public async Task<List<MunicipioDTO>> GetMunicipios(string uf)
        {
            using var client = new HttpClient();
            var response = await client.GetAsync($"https://servicodados.ibge.gov.br/api/v1/localidades/estados/{uf}/distritos");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var municipios = JsonConvert.DeserializeObject<List<MunicipioDTO>>(content);
                return municipios;
            }

            return new List<MunicipioDTO>(); 
        }

        public List<string> buscarUf()
        {
            return new List<string>
            {
                "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
                "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE","PI",
                "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
            };
        }

    }
}

WebCadastroProcessos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCadastroProcessos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCadastroProcessos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Processo" asp-action="Index">Processos Seletivo - FSBR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Processo" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 28/10/2024 FSBR - Fabrica de software do Brasil <a asp-area="" asp-controller="Processo" asp-action="Index"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>